{% set name = "robotframework-pythonlibcore" %}
{% set version = "2.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6fa2c052f6c9c98bfe69b804b42618086d7b33115963a1da131d1f2d8b774835

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - robotframework

test:
  imports:
    - robotlibcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robotframework/PythonLibCore
  summary: Tools to ease creating larger test libraries for Robot Framework using Python.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  description: |-
    The Robot Framework hybrid and dynamic library API gives more flexibility for
    library than the static library API, but they also sets requirements for
    libraries which needs to be implemented in the library side. PythonLibCore
    eases the problem by providing simpler interface and handling all the
    requirements towards the Robot Framework library APIs.

extra:
  recipe-maintainers:
    - bollwyvl
    - martinRenou
